# -------------------------------
# API backend (Streaming VM)
# -------------------------------
[[redirects]]
from = "/api/*"
to = "http://34.93.226.233/api/:splat"
status = 200
force = true

# -------------------------------
# HLS playback (Streaming VM)
# -------------------------------
[[redirects]]
from = "/hls/*"
to = "http://34.93.226.233/hls/:splat"
status = 200
force = true

# -------------------------------
# Buffer / Replay (Streaming VM)
# -------------------------------
[[redirects]]
from = "/buffer/*"
to = "http://34.93.226.233/buffer/:splat"
status = 200
force = true

# -------------------------------
# SPA fallback
# -------------------------------
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
