# Proxy for Incident Bridge (webhook service)
[[redirects]]
  from = "/api/bridge/*"
  to = "http://34.93.170.150:9000/:splat"
  status = 200
  force = true
# Proxy for RTMP backend (streams service)
[[redirects]]
  from = "/api/*"
  to = "http://34.93.170.150:4000/:splat"
  status = 200
  force = true

# Proxy for analytics backend
[[redirects]]
  from = "/analytics-api/*"
  to = "http://35.244.22.167:8000/:splat"
  status = 200
  force = true

# Proxy for HLS video segments/playlists
[[redirects]]
  from = "/hls/*"
  to = "http://34.93.170.150/hls/:splat"
  status = 200
  force = true

# SPA fallback: any other route -> index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
