# -------------------------------
# API backend (Streaming VM)
# -------------------------------
[[redirects]]
from = "/api/*"
to = "http://35.193.55.170:4000/:splat"
status = 200
force = true

# -------------------------------
# Analytics backend
# -------------------------------
[[redirects]]
from = "/hls/*"
to = "http://35.193.55.170/hls/:splat"
status = 200
force = true

# -------------------------------
# HLS playback (Streaming VM)
# -------------------------------
[[redirects]]
from = "/hls/*"
to = "http://35.193.55.170/hls/:splat"
status = 200
force = true

# -------------------------------
# SPA fallback
# -------------------------------
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
