# -------------------------------
# RTMP / Streams backend (ingest VM)
# -------------------------------
[[redirects]]
from = "/api/*"
to = "http://35.244.22.167:4000/:splat"
status = 200
force = true

# -------------------------------
# Analytics backend
# -------------------------------
[[redirects]]
from = "/analytics-api/*"
to = "http://34.93.170.150:8000/:splat"
status = 200
force = true

# -------------------------------
# HLS playback (ingest VM)
# -------------------------------
[[redirects]]
from = "/hls/*"
to = "http://35.244.22.167/hls/:splat"
status = 200
force = true

# -------------------------------
# SPA fallback
# -------------------------------
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
